# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/strawberry/acy/develop2/eiv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/strawberry/acy/develop2/eiv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/strawberry/acy/develop2/eiv/CMakeFiles /home/strawberry/acy/develop2/eiv/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/strawberry/acy/develop2/eiv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eiv

# Build rule for target.
eiv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eiv
.PHONY : eiv

# fast build rule for target.
eiv/fast:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/build
.PHONY : eiv/fast

eiv.o: eiv.cpp.o

.PHONY : eiv.o

# target to build an object file
eiv.cpp.o:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eiv.cpp.o
.PHONY : eiv.cpp.o

eiv.i: eiv.cpp.i

.PHONY : eiv.i

# target to preprocess a source file
eiv.cpp.i:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eiv.cpp.i
.PHONY : eiv.cpp.i

eiv.s: eiv.cpp.s

.PHONY : eiv.s

# target to generate assembly for a file
eiv.cpp.s:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eiv.cpp.s
.PHONY : eiv.cpp.s

eiv.obj: eiv.rc.obj

.PHONY : eiv.obj

# target to build an object file
eiv.rc.obj:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eiv.rc.obj
.PHONY : eiv.rc.obj

eiv2.o: eiv2.cpp.o

.PHONY : eiv2.o

# target to build an object file
eiv2.cpp.o:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eiv2.cpp.o
.PHONY : eiv2.cpp.o

eiv2.i: eiv2.cpp.i

.PHONY : eiv2.i

# target to preprocess a source file
eiv2.cpp.i:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eiv2.cpp.i
.PHONY : eiv2.cpp.i

eiv2.s: eiv2.cpp.s

.PHONY : eiv2.s

# target to generate assembly for a file
eiv2.cpp.s:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eiv2.cpp.s
.PHONY : eiv2.cpp.s

eivwmh.o: eivwmh.cpp.o

.PHONY : eivwmh.o

# target to build an object file
eivwmh.cpp.o:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eivwmh.cpp.o
.PHONY : eivwmh.cpp.o

eivwmh.i: eivwmh.cpp.i

.PHONY : eivwmh.i

# target to preprocess a source file
eivwmh.cpp.i:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eivwmh.cpp.i
.PHONY : eivwmh.cpp.i

eivwmh.s: eivwmh.cpp.s

.PHONY : eivwmh.s

# target to generate assembly for a file
eivwmh.cpp.s:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/eivwmh.cpp.s
.PHONY : eivwmh.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/main.cpp.s
.PHONY : main.cpp.s

savepct.o: savepct.cpp.o

.PHONY : savepct.o

# target to build an object file
savepct.cpp.o:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/savepct.cpp.o
.PHONY : savepct.cpp.o

savepct.i: savepct.cpp.i

.PHONY : savepct.i

# target to preprocess a source file
savepct.cpp.i:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/savepct.cpp.i
.PHONY : savepct.cpp.i

savepct.s: savepct.cpp.s

.PHONY : savepct.s

# target to generate assembly for a file
savepct.cpp.s:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/savepct.cpp.s
.PHONY : savepct.cpp.s

towallpaper.o: towallpaper.cpp.o

.PHONY : towallpaper.o

# target to build an object file
towallpaper.cpp.o:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/towallpaper.cpp.o
.PHONY : towallpaper.cpp.o

towallpaper.i: towallpaper.cpp.i

.PHONY : towallpaper.i

# target to preprocess a source file
towallpaper.cpp.i:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/towallpaper.cpp.i
.PHONY : towallpaper.cpp.i

towallpaper.s: towallpaper.cpp.s

.PHONY : towallpaper.s

# target to generate assembly for a file
towallpaper.cpp.s:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/towallpaper.cpp.s
.PHONY : towallpaper.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/eiv.dir/build.make CMakeFiles/eiv.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... eiv"
	@echo "... eiv.o"
	@echo "... eiv.i"
	@echo "... eiv.s"
	@echo "... eiv.obj"
	@echo "... eiv2.o"
	@echo "... eiv2.i"
	@echo "... eiv2.s"
	@echo "... eivwmh.o"
	@echo "... eivwmh.i"
	@echo "... eivwmh.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... savepct.o"
	@echo "... savepct.i"
	@echo "... savepct.s"
	@echo "... towallpaper.o"
	@echo "... towallpaper.i"
	@echo "... towallpaper.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

